services:
  - type: web
    name: gmprofits-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ODDS_API_KEY
        sync: false
      - key: CHAT_ID
        sync: false
      - key: TOPIC_ID
        sync: false
    pythonVersion: 3.10
